### ISSUE TITLE
Enable pushing snapshots to sonatype

### ISSUE THREAD

**Issue by mbknor** [NextGenTel/akka-tools#13]
It would be much better to _try out_ new fixes and features if snapshots where auto-deployed to sonatype

**Comment by zapodot** [comment]
should be fairly easy to do a simple fix to the travis build descriptor is all that it takes :-)

**Comment by zapodot** [comment]
It looks like I have tried to enable it earlier without any success :-)  I will give it another go

**Comment by zapodot** [comment]
Ok: https://oss.sonatype.org/#nexus-search;gav~no.nextgentel.oss.akka-tools~akka-tools-cluster_2.11~1.0.4-SNAPSHOT~~

I will try to re-enable coveralls later

**Comment by mbknor** [comment]
very good!

Does it (only) build the master branch? (That is fine if so)

**Comment by zapodot** [comment]
Yes, only builds for the master branch are published

**Comment by ovevang** [comment]
```
   ("`-''-/").___..--''"`-._ 
   `6_ 6  )   `-.  (     ).`-.__.`) 
   (_Y_.)'  ._   )  `._ `. ``-..-`  
  _..`--'_..-_/  /--'_.' ,'  
(il),-''  (li),'  ((!.-'
```

edit: now with animal instead of b0rked thumbs-up
