### ISSUE TITLE
Provide an example for using Seed Node Resolution + Split Brain Detection

### ISSUE THREAD

**Issue by calvinlfer** [NextGenTel/akka-tools#16]
Hello,

It would be great if a sample project was there with more detailed instructions on how to set up the Seed Node resolution and Split Brain detection. Many thanks for providing such valuable tools

Cheers
Cal

**Comment by calvinlfer** [comment]
Also wanted to know if it was possible to use another database like Postgres with the help of something like [this](https://github.com/dnvriend/akka-persistence-jdbc)

**Comment by mbknor** [comment]
Hi,

If I find the time, I'll write up an example.

Regarding Postgres:

The 'Seed node resolving' and split-brain-detection does not itself use eventsourcing and can therefor not use 'dnvriend/akka-persistence-jdbc'.

But akka-tools's GeneralAggregate (PersistentActor) - with friends - is not tied to akka-tools jdbc-journal and can therefor also use 'dnvriend/akka-persistence-jdbc'.

But I am not use if 'dnvriend/akka-persistence-jdbc' supports queryByTag.

**Comment by calvinlfer** [comment]
Ah I misunderstood, so is it possible to make use of Postgres or another open source platform for the Split Brain Detection + Seed Node Resolver?

Thanks and looking forward to your example
Cheers
Cal

**Comment by mbknor** [comment]
No.

For the seed node resolving an Split brain detection you have to use
akka-tools code.

It is only testet on Oracle and H2 in Oracle mode, but it might also work
with postgres.

-Morten

Den søn. 1. mai 2016, 22.17 skrev Cal notifications@github.com:

**Comment by calvinlfer** [comment]
Okay thanks for the clarification
