### ISSUE TITLE
Release 0.9.0

### ISSUE THREAD

**Issue by zapodot** [NextGenTel/akka-tools#5]
As the current state of affairs is pretty good, I think we can create a 0.9.0 release now and keep up the development on new features

**Comment by mbknor** [comment]
I have prepared and tested the release in this branch:

https://github.com/NextGenTel/akka-tools/tree/release-0.9.0

All @ovevang needs to do is to check out the branch and run 

```
sbt publish
```

No need to push anything to github

**Comment by zapodot** [comment]
Nice!

**Comment by mbknor** [comment]
A little correction: After the release is available in maven central we must update "current version" in README in master-branch

**Comment by ovevang** [comment]
Done, including current version update in docs. Sonatype release completed, maven central update pending.

Edit: confirmed OK in mvn central: http://search.maven.org/#search%7Cga%7C1%7Cakka-tools

**Comment by mbknor** [comment]
Nice
